// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/snowflake/snowflake.proto

package go_micro_srv_snowflake

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	WorkerId             int64    `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7256b1f7ad55f55c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetWorkerId() int64 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

type Response struct {
	CodeId               int64    `protobuf:"varint,1,opt,name=codeId,proto3" json:"codeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7256b1f7ad55f55c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCodeId() int64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.snowflake.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.snowflake.Response")
}

func init() { proto.RegisterFile("proto/snowflake/snowflake.proto", fileDescriptor_7256b1f7ad55f55c) }

var fileDescriptor_7256b1f7ad55f55c = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0xcb, 0x2f, 0x4f, 0xcb, 0x49, 0xcc, 0x4e, 0x45, 0xb0, 0xf4, 0xc0, 0x32,
	0x42, 0x62, 0xe9, 0xf9, 0x7a, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x70,
	0x59, 0x25, 0x55, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x8e,
	0xf2, 0xfc, 0xa2, 0xec, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x38,
	0x5f, 0x49, 0x89, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b,
	0x2d, 0x39, 0x3f, 0x25, 0x15, 0xae, 0x0a, 0xca, 0x33, 0x4a, 0xe2, 0xe2, 0x0c, 0x86, 0x99, 0x2b,
	0x14, 0xca, 0xc5, 0xe7, 0x9e, 0x9a, 0x97, 0x5a, 0x94, 0x58, 0x92, 0xea, 0x9f, 0x97, 0x53, 0xe9,
	0x99, 0x22, 0x24, 0xaf, 0x87, 0xdd, 0x09, 0x7a, 0x50, 0xfb, 0xa5, 0x14, 0x70, 0x2b, 0x80, 0xd8,
	0xac, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x01, 0x25, 0xc9,
	0x05, 0xf0, 0x00, 0x00, 0x00,
}
