// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Role                 int64    `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Response) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetRole() int64 {
	if m != nil {
		return m.Role
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x4e, 0xc4, 0x30,
	0x0c, 0x86, 0x69, 0xaf, 0x3d, 0x0e, 0x0f, 0x48, 0x58, 0x80, 0xa2, 0xb2, 0xa0, 0x4e, 0x4c, 0x41,
	0x82, 0x27, 0x38, 0x58, 0x99, 0x2a, 0xf1, 0x00, 0x85, 0x5a, 0x47, 0xa5, 0x5e, 0x1c, 0xe2, 0x14,
	0x9e, 0x82, 0x77, 0x46, 0x71, 0x0a, 0x0b, 0x6c, 0xb7, 0x44, 0xfe, 0xfe, 0x5f, 0xff, 0xaf, 0xd8,
	0x70, 0xe1, 0x03, 0x47, 0xbe, 0x9d, 0x85, 0x82, 0x3e, 0x56, 0x19, 0xcf, 0x76, 0x6c, 0xf7, 0xe3,
	0x6b, 0x60, 0x2b, 0xe1, 0xc3, 0x26, 0xa3, 0xdd, 0xc2, 0x71, 0x47, 0xef, 0x33, 0x49, 0xc4, 0x06,
	0x36, 0x49, 0x72, 0xfd, 0x9e, 0x4c, 0x71, 0x5d, 0xdc, 0x9c, 0x74, 0xbf, 0x9c, 0x3c, 0xdf, 0x8b,
	0x7c, 0x72, 0x18, 0x4c, 0x99, 0xbd, 0x1f, 0x6e, 0x3d, 0x6c, 0x3a, 0x12, 0xcf, 0x4e, 0x08, 0x4f,
	0xa1, 0x1c, 0x07, 0x4d, 0xaf, 0xba, 0x72, 0x1c, 0x10, 0xa1, 0xd2, 0xbe, 0x9c, 0xd1, 0x19, 0xcf,
	0xa1, 0xf6, 0x6f, 0xec, 0xc8, 0xac, 0x54, 0xcc, 0x80, 0x97, 0xb0, 0x96, 0xd8, 0xc7, 0x59, 0x4c,
	0xa5, 0xe9, 0x85, 0x52, 0x43, 0xe0, 0x89, 0x4c, 0xad, 0xaa, 0xce, 0x77, 0x5f, 0x05, 0x54, 0xcf,
	0x42, 0x01, 0xb7, 0x50, 0x3d, 0xf6, 0xd3, 0x84, 0x8d, 0xfd, 0xb3, 0x99, 0x5d, 0xd6, 0x6a, 0xae,
	0xfe, 0xf5, 0xf2, 0x7f, 0xdb, 0x23, 0x7c, 0x80, 0xfa, 0x89, 0x77, 0xa3, 0x3b, 0xa0, 0xe3, 0x65,
	0xad, 0xe7, 0xbd, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x00, 0x5d, 0x33, 0x7f, 0x77, 0x01, 0x00,
	0x00,
}
